import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Navbar from '../components/Navbar';
import Header from '../components/Header';
import Services from '../components/Services';
import Testimonials from '../components/Testimonials'
import Contact from '../components/Contact';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <Navbar />
        <section className="pt-36">
          <Header />
        </section>
        <section className="py-36">
          <Services />
        </section>
        <section className=" py-22">
          <Testimonials />
        </section>
        <section className=" py-22">
          <Contact />
        </section>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
